homepage/urls.py
from django.contrib import admin
from . import views
from django.urls import path

app_name='homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('story8/', views.story8, name='story8'),
    path('story9/', views.story9, name='story9'),
    path('story9/afterlogin', views.afterlogin, name='afterlogin'),
    path('story9/logout', views.logoutstory9, name='logoutstory9'),
    # path('', views.redirecting, name='redirecting')
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'index.html')
    
def story8(request):
    return render(request, 'story8.html')
    
def story9(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('homepage:afterlogin')
    else:
        form = AuthenticationForm()
    return render(request, 'story9.html', {'form':form})
        
def afterlogin(request):
    return render(request, 'afterlogin.html')
    
def logoutstory9(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			logout(request)
	return redirect('homepage:story9')
    
    
    

homepage/templates/afterlogin.html
{% extends 'base.html' %}
{% load static %}
<html>
<head>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" >

  
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
</head>

{% block content %}
<body class="baby-blue">
	<br><br><br><br><br><br>
	{% if user.is_authenticated %}
	<h3>Hello {{ user.username }}!</h3>
	<form class="logout-link" action="{%url 'homepage:logoutstory9' %}" method="post">
		{% csrf_token %}
		<button type="submit" class="btn btn-outline-info">Logout</button>
	</form>
	{% endif %} 
</body>
{% endblock %}
</html>

homepage/templates/base.html
{% load static %}

<html>
<head>
	<title>Nazila Rahma</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" >
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="{% static 'js/theme.js'  %}"></script>
	<script src="{% static 'js/eight.js'  %}"></script>
	
</head>
  
	
<nav class="navbar navbar-expand-lg warnaNavbar fixed-top">
	<a class="navbar-brand" href="{% url 'homepage:story9' %}"> Login</a>
	<a class="navbar-brand" href="{% url 'homepage:index' %}"> Theme</a>
	<a class="navbar-brand" href="{% url 'homepage:story8' %}"> Books</a>
	
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	<div class="navbar-nav ml-auto">
	<a class="nav-item nav-link">Nazila Rahma</a> 
	</div>
	</div>
</nav>
{% block content %}
	{% endblock %}

</html>

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}

<html>

	

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Nazila Rahma</title>
  <link rel="shortcut icon" href="">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" >

  
<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	  <script src="{% static 'js/theme.js'  %}"></script>
  	
  
</head>
{% block content %}
<body class="baby-blue">
	<br><br><br>
  <button type="button" class="btn btn-light warna" id="theme-button"> theme</button> <p id="greeting">this is the baby-blue theme :)</p>
	<div class="all">
		
		<div>
			<br><br>
	<h2>Hello, aku nazila</h2>
	<br>
	
		<ul>
		<li style='list-style-type: none;'><button class="button-aktivitas buttonku btn btn-outline-secondary" id='act'>aktivitas</button></li>
		<p class="aktivitas" >kuliah<br>makan<br>tidur</p>
		<li style='list-style-type: none;'><button class="button-organisasi buttonku btn btn-outline-secondary" id='org'>organisasi</button></li>
		<p class="organisasi">fuki<br>sistem<br></p>
			<li style='list-style-type: none;'><button class="button-prestasi buttonku btn btn-outline-secondary" id='pres'>prestasi</button></li>
			<p class="prestasi">ga punya<br></p>
		</ul>
		

		

		
		
		<br>
	    
	</div>
	</div>
	
</body>
{% endblock %}
</html>

homepage/templates/story8.html
{% extends 'base.html' %}
{% load static %}

<html>
<head>
	<title>story8 nazila</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" >

  
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="{% static 'js/eight.js'  %}"></script>
</head>
{% block content %}
<body class="baby-blue">
	
	<div class="container">
		<br><br><br><br><br>
	<h2> Search book </h2>
	<form class="form-inline form-control-lg md-form mr-auto mb-4 container">
		<input id="buku" class="form-control mr-sm-2" placeholder="Search" type="search" id="searchBox" name="" value="" style="width:70vw;font-size:25px">
	</form>
	</div>
	<div class="table-responsive container">
		<table class= "table table-light table-hover">
			<thead class = "tabelku" style="background-color:#ffe1e6;font-size:25px;">
				<tr class="text-center">
					<th scope="col" class="align-middle">No.</th>
	                <th scope="col" class="align-middle">Cover</th>
	                <th scope="col" class="align-middle">Title</th>
	                <th scope="col" class="align-middle">Authors</th>
	                <th scope="col" class="align-middle">Published Date</th>
				</tr>
			</thead>
			<tbody class="tulis"></tbody>
		</table>
	</div>
	
</body>
{% endblock %}
</html>

homepage/templates/story9.html
{% extends 'base.html' %}
{% load static %}
<html>
<head>
	<title>Login</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" >

  
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
</head>

{% block content %}
<body class="baby-blue">
	<br><br><br><br><br><br>
    <h1>Login</h1>
     <form class="site-form" action="{%url 'homepage:story9' %}" method="post">
      {% csrf_token %}
      <div>
      {{form.as_p}}
      </div>
      <input type="submit" value="Login" class="btn btn-outline-info">
     </form>
</body>
{% endblock %}
</html>